#!/bin/sh
APPDIR=`dirname $0`;
java -cp "$APPDIR/src:$APPDIR/bin:/usr/local/Cellar/gwt/2.8.2/libexec/gwt-user.jar:/usr/local/Cellar/gwt/2.8.2/libexec/gwt-dev.jar" com.google.gwt.i18n.tools.I18NSync -out $APPDIR/src com.js.client.DashboardConstants  ;

